FROM debian:bullseye-slim AS aws-cli-installer

RUN apt-get update && apt-get install -y curl unzip

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

FROM cypress/included:15.21.1

COPY --from=aws-cli-installer /usr/local/aws-cli /usr/local/aws-cli
COPY --from=aws-cli-installer /usr/local/bin/aws /usr/local/bin/aws

ENV PATH="/usr/local/aws-cli/v2/current/bin:$PATH"

RUN apt-get update && apt-get install -y build-essential curl zip && \
    npm install -g n && n 20 && \
    cypress install
