FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    curl \
    jq \
    unzip \
    bash \
    less \
    ca-certificates \
    sudo \
    gnupg \
    lsb-release \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - \
    && sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
    && sudo apt-get update \
    && sudo apt-get install -y terraform

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && sudo ./aws/install \
    && rm -rf awscliv2.zip aws

RUN curl -fsSLO "https://dl.k8s.io/release/$(curl -fsSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
&& chmod +x kubectl \
&& mv kubectl /usr/local/bin/kubectl

WORKDIR /workspace

CMD ["/bin/bash"]