# Utiliser une image de base Ubuntu
FROM ubuntu:22.04

# Mettre à jour les paquets et installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    curl \
    jq \
    unzip \
    bash \
    less \
    ca-certificates \
    sudo \
    gnupg \
    lsb-release \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# Installer Terraform
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - \
    && sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
    && sudo apt-get update \
    && sudo apt-get install -y terraform

# Installer AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && sudo ./aws/install \
    && rm -rf awscliv2.zip aws

# Définir le répertoire de travail
WORKDIR /workspace

# Par défaut démarrer un shell interactif
CMD ["/bin/bash"]