FROM apache/airflow:2.11.2-python3.12

USER root

USER airflow

# Install the required Python package for Airflow as the airflow user
RUN pip install --no-cache-dir openpyxl==3.1.5 opensearch-py==2.8.0
