name: Build and Publish Snipe-IT Custom Image on Commit

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.snipeit-custom

jobs:
  publish_snipeit_custom_image:
    name: Publish Snipe-IT Custom Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Push the image on the docker registry
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/snipeit-custom
          tag_format: "latest"
          dockerfile: "Dockerfile.snipeit-custom"