name: Build and Publish Python Requests Image on Using Semver Tag

on:
  push:
    tags:
      - 'python-requests-v*'
    paths:
      - Dockerfile.python-requests

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version Tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/python-requests-v}" >> $GITHUB_ENV

      - name: Publish Python Requests Image
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/python-requests
          tag_format: "${{ env.VERSION }}"
          dockerfile: "Dockerfile.python-requests"