name: Build and Publish Terracd AWS Image on Semver Tag

on:
  push:
    tags:
      - 'terracd-aws-v*'
    paths:
      - terracd-aws/Dockerfile

jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Extract Version Tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/terracd-aws-v}" >> $GITHUB_ENV

      - name: Publish Terracd AWS Image
        uses: Ferlab-Ste-Justine/action-push-image@v2
        with:
          username: ${{ secrets.FERLAB_DOCKER_HUB_USER }}
          password: ${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}
          image: ferlabcrsj/terracd-aws
          tag_format: "${{ env.VERSION }}"
          dockerfile: "terracd-aws/Dockerfile"
